# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-POC',
                'doc_host': 'https://sherpamnk.github.io',
                'git_url': 'https://github.com/sherpamnk/nbdev-POC',
                'lib_path': 'nbdev_POC'},
  'syms': {'nbdev_POC.core': {'nbdev_POC.core.foo': ('core.html#foo', 'nbdev_POC/core.py')}}}
